version: '2'
services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres-devnet
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - core
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: core_devnet
     POSTGRES_USER: node

  core:
    image: arkecosystem/core:devnet
    container_name: core-devnet
    restart: always
    ports:
     - "4102:4102"
     - "4103:4103"
     - "4140:4140"
     - "127.0.0.1:4104:4104"
     - "127.0.0.1:4105:4105"
     - "127.0.0.1:8080:8080"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
     - ~/.config/qredit-core:/home/node/.config/qredit-core
     - ~/.local/share/qredit-core:/home/node/.local/share/qredit-core
     - ~/.local/state/qredit-core:/home/node/.local/state/qredit-core
     - /etc/localtime:/etc/localtime:ro
     - ./enc:/run/secrets
    networks:
      - core
    env_file: ./devnet.env
    tty: true
    links:
     - postgres
    depends_on:
      - postgres
volumes:
  postgres:
  core:
networks:
  core:
